# Generated by Django 3.1 on 2020-08-10 14:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=50)),
                ('about', models.CharField(default=True, max_length=500)),
                ('mobile_no', models.IntegerField(default=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('background_image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
